const DEFAULT_FIELDS=[
 {key:"photo",label:"Photo",type:"image"},
 {key:"name",label:"Name",type:"text"},
 {key:"cnic",label:"CNIC Number",type:"text"},
 {key:"dob",label:"Date of Birth",type:"text"},
 {key:"issue",label:"Date of Issue",type:"text"},
 {key:"expiry",label:"Date of Expiry",type:"text"},
 {key:"father",label:"Father Name",type:"text"},
 {key:"mother",label:"Mother Name",type:"text"},
 {key:"relation",label:"Relation",type:"text"},
 {key:"signature",label:"Signature",type:"image"},
 {key:"address",label:"Address",type:"text"},
 {key:"permanent",label:"Permanent Address",type:"text"}
];
let db={templates:[],fields:DEFAULT_FIELDS,persons:[],editTemplate:null,selectedTemplate:null};
let selected=null;
const $=id=>document.getElementById(id);
function load(){let x=localStorage.getItem("victim_app_v3");if(x){try{db=JSON.parse(x)}catch(e){}} if(!db.fields)db.fields=DEFAULT_FIELDS;if(!db.templates)db.templates=[];if(!db.persons)db.persons=[]}
function save(){localStorage.setItem("victim_app_v3",JSON.stringify(db))}
function login(){if($("loginUser").value==="admin"&&$("loginPass").value==="admin123"){$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");init()}else $("loginMsg").innerText="Wrong login"}
function logout(){location.reload()}
function toggleNav(){$("nav").classList.toggle("open")}
function openTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");if(innerWidth<801)$("nav").classList.remove("open");refreshSelects();if(id==="adminDesigner")renderDesigner();if(id==="userEntry")renderPersons();if(id==="previewExport")renderPreview()}
function fileData(file){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function saveTemplate(){let name=$("templateName").value.trim()||"Template";let cap=parseInt($("templateCapacity").value||4);let bgFile=$("templateBg").files[0];let bg=bgFile?await fileData(bgFile):null;let t=db.editTemplate?db.templates.find(x=>x.id===db.editTemplate):null;if(!t){t={id:String(Date.now()),name,capacity:cap,bg:"",layouts:{}};db.templates.push(t)}t.name=name;t.capacity=cap;if(bg)t.bg=bg;if(!t.bg){alert("Blank background upload کریں");return}for(let i=1;i<=cap;i++)if(!t.layouts[i])t.layouts[i]=[];db.selectedTemplate=t.id;db.editTemplate=null;save();$("templateName").value="";$("templateCapacity").value=4;$("templateBg").value="";renderTemplates();refreshSelects();alert("Template Saved")}
function newTemplate(){db.editTemplate=null;$("templateName").value="";$("templateCapacity").value=4;$("templateBg").value=""}
function renderTemplates(){let el=$("templateList");el.innerHTML="";db.templates.forEach(t=>{let d=document.createElement("div");d.className="item";d.innerHTML=`<div><b>${t.name}</b><br>${t.capacity} persons/page</div><div><button onclick="editTpl('${t.id}')">Edit</button> <button onclick="designTpl('${t.id}')">Design</button> <button class="danger" onclick="delTpl('${t.id}')">Delete</button></div>`;el.appendChild(d)})}
function editTpl(id){let t=db.templates.find(x=>x.id===id);db.editTemplate=id;$("templateName").value=t.name;$("templateCapacity").value=t.capacity;openTab("adminTemplates")}
function designTpl(id){db.selectedTemplate=id;openTab("adminDesigner")}
function delTpl(id){if(confirm("Delete?")){db.templates=db.templates.filter(x=>x.id!==id);save();renderTemplates();refreshSelects()}}
function addField(){let name=$("fieldName").value.trim();if(!name)return;let type=$("fieldType").value;let key=name.toLowerCase().replace(/[^a-z0-9]+/g,"_")+"_"+Date.now();db.fields.push({key,label:name,type});$("fieldName").value="";save();renderFields();refreshSelects()}
function renderFields(){let el=$("fieldList");el.innerHTML="";db.fields.forEach(f=>{let d=document.createElement("div");d.className="item";d.innerHTML=`<span>${f.label} (${f.type})</span>${DEFAULT_FIELDS.some(x=>x.key===f.key)?"":`<button class="danger" onclick="removeField('${f.key}')">Remove</button>`}`;el.appendChild(d)})}
function removeField(k){db.fields=db.fields.filter(f=>f.key!==k);db.templates.forEach(t=>Object.values(t.layouts).forEach(a=>{for(let i=a.length-1;i>=0;i--)if(a[i].key===k)a.splice(i,1)}));save();renderFields();refreshSelects()}
function refreshSelects(){["designTemplate","entryTemplate"].forEach(id=>{let s=$(id);if(!s)return;let v=s.value||db.selectedTemplate;s.innerHTML="";db.templates.forEach(t=>s.add(new Option(t.name,t.id)));if(v)s.value=v});let t=getTemplate();let p=$("designPerson");if(p){let v=p.value;p.innerHTML="";if(t)for(let i=1;i<=t.capacity;i++)p.add(new Option("Person "+i,i));if(v)p.value=v}let f=$("designField");if(f){let v=f.value;f.innerHTML="";db.fields.forEach(x=>f.add(new Option(x.label+" ("+x.type+")",x.key)));if(v)f.value=v}}
function getTemplate(){let id=$("designTemplate")?.value||$("entryTemplate")?.value||db.selectedTemplate;return db.templates.find(t=>t.id===id)||db.templates[0]}
function loadTemplateForDesign(){db.selectedTemplate=$("designTemplate").value;refreshSelects();renderDesigner()}
function renderDesigner(){let t=getTemplate();let c=$("designer");c.innerHTML="";selected=null;$("boxSettings").classList.add("hidden");if(!t){c.style.backgroundImage="none";return}c.style.backgroundImage=`url(${t.bg})`;let slot=$("designPerson").value||1;if(!t.layouts[slot])t.layouts[slot]=[];t.layouts[slot].forEach((b,i)=>drawBox(b,i))}
function drawBox(b,i){let c=$("designer");let el=document.createElement("div");el.className="box";el.dataset.i=i;el.style.left=b.x+"px";el.style.top=b.y+"px";el.style.width=b.w+"px";el.style.height=b.h+"px";el.style.fontSize=(b.font||18)+"px";el.style.color=b.color||"#000";el.style.fontWeight=b.bold?"700":"400";el.style.justifyContent=b.align==="center"?"center":b.align==="right"?"flex-end":"flex-start";el.innerHTML=`${b.label||fieldLabel(b.key)}<span class="handle"></span>`;c.appendChild(el);drag(el);el.onclick=e=>{e.stopPropagation();selectBox(el)}}
function currentLayout(){let t=getTemplate();let slot=$("designPerson").value||1;if(!t.layouts[slot])t.layouts[slot]=[];return t.layouts[slot]}
function fieldLabel(k){return db.fields.find(f=>f.key===k)?.label||k}
function fieldType(k){return db.fields.find(f=>f.key===k)?.type||"text"}
function addBox(){let k=$("designField").value;let b={key:k,label:fieldLabel(k),x:40,y:40,w:fieldType(k)==="image"?110:190,h:fieldType(k)==="image"?130:34,font:18,color:"#000000",bold:false,align:"left"};currentLayout().push(b);save();renderDesigner()}
function selectBox(el){document.querySelectorAll(".box").forEach(x=>x.classList.remove("sel"));el.classList.add("sel");selected=el;let b=currentLayout()[+el.dataset.i];$("boxSettings").classList.remove("hidden");$("sLabel").value=b.label||fieldLabel(b.key);$("sFont").value=b.font||18;$("sColor").value=b.color||"#000000";$("sBold").checked=!!b.bold;$("sAlign").value=b.align||"left"}
function updateBox(){if(!selected)return;let b=currentLayout()[+selected.dataset.i];b.label=$("sLabel").value;b.font=parseInt($("sFont").value||18);b.color=$("sColor").value;b.bold=$("sBold").checked;b.align=$("sAlign").value;save();renderDesigner()}
function deleteBox(){if(!selected)return;currentLayout().splice(+selected.dataset.i,1);save();renderDesigner()}
function saveAll(){save();alert("Saved")}
function drag(el){let mode="",sx,sy,sl,st,sw,sh;el.onpointerdown=e=>{mode=e.target.className==="handle"?"resize":"move";sx=e.clientX;sy=e.clientY;sl=parseFloat(el.style.left);st=parseFloat(el.style.top);sw=parseFloat(el.style.width);sh=parseFloat(el.style.height);el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!mode)return;let dx=e.clientX-sx,dy=e.clientY-sy;if(mode==="move"){el.style.left=Math.max(0,sl+dx)+"px";el.style.top=Math.max(0,st+dy)+"px"}else{el.style.width=Math.max(25,sw+dx)+"px";el.style.height=Math.max(22,sh+dy)+"px"}};el.onpointerup=e=>{if(!mode)return;let b=currentLayout()[+el.dataset.i];b.x=parseFloat(el.style.left);b.y=parseFloat(el.style.top);b.w=parseFloat(el.style.width);b.h=parseFloat(el.style.height);mode="";save()}}
function usedFields(t){let s=new Set();if(!t)return[];Object.values(t.layouts||{}).forEach(a=>a.forEach(b=>s.add(b.key)));return db.fields.filter(f=>s.has(f.key))}
function addPerson(){let t=getTemplate();if(!t)return alert("Create template first");let p={id:String(Date.now()),data:{}};usedFields(t).forEach(f=>p.data[f.key]="");db.persons.push(p);save();renderPersons()}
function renderPersons(){let t=getTemplate();let el=$("persons");if(!el)return;el.innerHTML="";let fields=usedFields(t);db.persons.forEach((p,idx)=>{let div=document.createElement("div");div.className="person";div.innerHTML=`<h3>Person ${idx+1}<button class="danger" onclick="delPerson('${p.id}')">Delete</button></h3>`;fields.forEach(f=>{let val=p.data[f.key]||"";if(f.type==="image"){div.innerHTML+=`<label>${f.label}</label><input type="file" accept="image/*" onchange="setFile('${p.id}','${f.key}',this)">`;if(val)div.innerHTML+=`<img class="thumb" src="${val}">`}else if(f.key.includes("address")){div.innerHTML+=`<label>${f.label}</label><textarea onchange="setVal('${p.id}','${f.key}',this.value)">${escapeHtml(val)}</textarea>`}else{div.innerHTML+=`<label>${f.label}</label><input value="${escapeHtml(val)}" onchange="setVal('${p.id}','${f.key}',this.value)">`}});el.appendChild(div)});if(!db.persons.length)el.innerHTML="<div class='card'>Add Person دبائیں۔</div>"}
function escapeHtml(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function setVal(id,k,v){let p=db.persons.find(x=>x.id===id);p.data[k]=v;save()}
async function setFile(id,k,input){let p=db.persons.find(x=>x.id===id);if(input.files[0])p.data[k]=await fileData(input.files[0]);save();renderPersons()}
function delPerson(id){db.persons=db.persons.filter(p=>p.id!==id);save();renderPersons()}
function clearPersons(){if(confirm("Clear entry data? Templates safe.")){db.persons=[];save();renderPersons();$("preview").innerHTML=""}}
function renderPreview(){let t=getTemplate();let out=$("preview");out.innerHTML="";if(!t){out.innerHTML="<div class='card'>No template</div>";return}let cap=+t.capacity;let pages=Math.max(1,Math.ceil(db.persons.length/cap));for(let pg=0;pg<pages;pg++){let page=document.createElement("div");page.className="preview-page exportPage";page.style.backgroundImage=`url(${t.bg})`;for(let slot=1;slot<=cap;slot++){let person=db.persons[pg*cap+slot-1];if(!person)continue;(t.layouts[slot]||[]).forEach(b=>{let val=person.data[b.key]||"";if(fieldType(b.key)==="image"){if(val){let img=document.createElement("img");img.className="outImg";img.src=val;img.style.left=b.x+"px";img.style.top=b.y+"px";img.style.width=b.w+"px";img.style.height=b.h+"px";page.appendChild(img)}}else{let d=document.createElement("div");d.className="outText";d.textContent=val;d.style.left=b.x+"px";d.style.top=b.y+"px";d.style.width=b.w+"px";d.style.height=b.h+"px";d.style.fontSize=(b.font||18)+"px";d.style.color=b.color||"#000";d.style.fontWeight=b.bold?"700":"400";d.style.textAlign=b.align||"left";page.appendChild(d)}})}out.appendChild(page)}}
async function downloadPDF(){renderPreview();let pages=[...document.querySelectorAll(".exportPage")];if(!pages.length)return;let {jsPDF}=window.jspdf;let pdf=new jsPDF({orientation:"landscape",unit:"px",format:[900,600]});for(let i=0;i<pages.length;i++){let c=await html2canvas(pages[i],{scale:2,useCORS:true,allowTaint:true});let img=c.toDataURL("image/jpeg",.95);if(i>0)pdf.addPage([900,600],"landscape");pdf.addImage(img,"JPEG",0,0,900,600)}pdf.save("victim-template.pdf");db.persons=[];save();renderPersons()}
async function downloadJPG(){renderPreview();let pages=[...document.querySelectorAll(".exportPage")];for(let i=0;i<pages.length;i++){let c=await html2canvas(pages[i],{scale:2,useCORS:true,allowTaint:true});let a=document.createElement("a");a.href=c.toDataURL("image/jpeg",.95);a.download=`page-${i+1}.jpg`;a.click();await new Promise(r=>setTimeout(r,300))}db.persons=[];save();renderPersons()}
function init(){renderFields();renderTemplates();refreshSelects();renderPersons()}
load()
